spring.config.import=optional:file:.env.properties

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
spring.rabbitmq.virtual-host=${RABBITMQ_VIRTUAL_HOST}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.addresses=${RABBITMQ_ADDRESS}