spring.rabbitmq.host=ackal-01.rmq.cloudamqp.com 
spring.rabbitmq.password=rAGCz9XyS_MAQtL4uEsx5IaJ5ep9JVCz
spring.rabbitmq.virtual-host=qytieuev
spring.rabbitmq.username=qytieuev
spring.rabbitmq.addresses=amqps://qytieuev:rAGCz9XyS_MAQtL4uEsx5IaJ5ep9JVCz@jackal.rmq.cloudamqp.com/qytieuev